### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by joshibeast** [ZephrFish/DoNotRunMe#1]
It's broken,
I can't get past this screen and I've tried everything:
![Wana_Decrypt0r_screenshot](https://user-images.githubusercontent.com/10061471/131642733-923ff24f-2be1-4bcb-8f45-4bc637330061.png)

I'll try to run it later on my company computer, maybe I'll have more luck.
(They gave me admin rights because I'm good with computers.)

**Comment by ZephrFish** [comment]
![image](https://user-images.githubusercontent.com/5783068/131643395-d35c408b-f8d9-4033-8879-1e0c9ad4027e.png)
